services:
  kapowarr:
    container_name: kapowarr
    build: .
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - "/home/heretic/Projects/robert_test/Kapowarr/db:/app/db"
      - "/home/heretic/Downloads:/app/temp_downloads"
      - "/home/heretic/comics:/comics"
    ports:
      - 5656:5656

volumes:
  kapowarr-db:
